language: go

go:
  - 1.5.x

install:
  - go get -d -v llvm.org/llvm/bindings/go/llvm
  - $GOPATH/src/llvm.org/llvm/bindings/go/build.sh -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host

script:
  - time go build
  - graincompiler/graincompiler
  - graincompiler/hello_program
