dist: trusty
sudo: required

language: go

go:
  - 1.4.x

before_install:
  - wget http://www.cmake.org/files/v3.4/cmake-3.7.1.tar.gz
  - tar -xvzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure
  - make
  - sudo make install
  - cmake --version
  - ls /usr/bin/cmake
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cmake --version

install:
  - go get -d -v llvm.org/llvm/bindings/go/llvm
  - $GOPATH/src/llvm.org/llvm/bindings/go/build.sh -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host

script:
  - time go build ./...
  - ./graincompiler
  - ./hello_program
