dist: trusty
sudo: required

language: go

matrix:
  include:
    - go: 1.4.x
      env: LLVM_GO_GET_FLAGS=""
    - go: 1.5.x
      env: LLVM_GO_GET_FLAGS="-insecure"

cache:
  directories:
    - $GOPATH/src/llvm.org/
    - cmake_install/cmake-3.7.1/

before_install:
  - script/install_cmake
  - script/install_llvm

install:
  - cd graincompiler
  - time go build

script:
  - ./graincompiler
  - ../script/run_e2e_tests
