dist: trusty
sudo: required

language: go

matrix:
  include:
    - go: 1.4.x
      env: LLVM_GO_GET_FLAGS=""
    - go: 1.5.x
      env: LLVM_GO_GET_FLAGS="-insecure"

cache:
  directories:
    - $GOPATH/src/llvm.org/
    - cmake_install/cmake-3.7.1/

before_install:
  - script/install_cmake
  - script/install_llvm

install:
  - cd graincompiler
  - time go build

script:
  - ./graincompiler
  - echo "abc" | ./hello_program > hello_output
  - cmp hello_output hello_expected || { echo 'Files are not the same.'; exit 1; }
  - echo "g" | ./get_put > get_put_output
  - cmp get_put_output ../hello/get_char_put_char_expected || { echo 'Files are not the same.'; exit 1; }
  - echo "g" | ./get_upper_put > get_upper_put_output
  - cmp get_upper_put_output ../hello/get_char_to_upper_put_char_expected || { echo 'Files are not the same.'; exit 1; }
