dist: trusty
sudo: required

language: go

matrix:
  include:
    - go: 1.4.x
      env: LLVM_GO_GET_FLAGS=""
    - go: 1.5.x
      env: LLVM_GO_GET_FLAGS="-insecure"

before_install:
  - cmake --version
  - wget http://www.cmake.org/files/v3.7/cmake-3.7.1.tar.gz
  - tar -xvzf cmake-3.7.1.tar.gz
  - cd cmake-3.7.1/
  - ./configure
  - make
  - sudo make install
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cd ..
  - rm -rf cmake-3.7.1/
  - cmake --version

install:
  - go get $LLVM_GO_GET_FLAGS -d -v llvm.org/llvm/bindings/go/llvm
  - $GOPATH/src/llvm.org/llvm/bindings/go/build.sh -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host

script:
  - cd graincompiler
  - time go build
  - ./graincompiler
  - echo "abc" | ./hello_program
  - echo "abc" | ./hello_program > hello_output
  - cmp --silent hello_output hello_expected || { echo 'Files are not the same.'; exit 1; }
