dist: trusty
sudo: required

language: go

matrix:
  include:
    - go: 1.4.x
      env: LLVM_GO_GET_FLAGS=""
    - go: 1.5.x
      env: LLVM_GO_GET_FLAGS="-insecure"

cache:
  directories:
    - $GOPATH/src/llvm.org/

before_install:
  - cmake --version
  - script/install_cmake
  - cmake --version

install:
  - script/install_llvm

script:
  - cd graincompiler
  - time go build
  - ./graincompiler
  - echo "abc" | ./hello_program > hello_output
  - cmp --silent hello_output hello_expected || { echo 'Files are not the same.'; exit 1; }
