#!/bin/bash

if [ ! -d "$GOPATH/src/llvm.org/llvm" ]; then
  go get $LLVM_GO_GET_FLAGS -d -v llvm.org/llvm/bindings/go/llvm
fi
$GOPATH/src/llvm.org/llvm/bindings/go/build.sh -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host
