#!/bin/bash

mkdir cmake_install
cd cmake_install/
wget http://www.cmake.org/files/v3.7/cmake-3.7.1.tar.gz
tar -xvzf cmake-3.7.1.tar.gz
cd cmake-3.7.1/
./configure
make
sudo make install
sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
cd ../..
