#!/bin/bash

[ $(echo "g" | ./get_put) == "g" ] || { echo "Output is different than expected."; exit 1; }
[ $(echo "g" | ./get_upper_put) == "G" ] || { echo "Output is different than expected."; exit 1; }
